apply plugin: 'maven-publish'
apply plugin: 'java'
apply plugin: 'signing'

repositories {
    mavenCentral()
    maven {
        // change to point to your repo, e.g. http://my.org/repo
        url = 'https://github.com/JoelBushart/typesafeconfig-guice'
    }
}

group = 'com.github.racc'
archivesBaseName = "typesafeconfig-guice"
version = '0.1.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

jar {
    manifest {
        attributes 'Implementation-Title': 'TypesafeConfigGuice',
                'Implementation-Version': version
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

task sourcesJar(type: Jar) {
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    from 'build/docs/javadoc'
}

artifacts {
    archives sourcesJar
    archives javadocJar
}

dependencies {
    implementation 'com.typesafe:config:1.4.3'
    implementation group: 'io.github.lukehutch', name: 'fast-classpath-scanner', version: '3.1.5'
    implementation 'org.reflections:reflections:0.10.2'
    implementation 'com.google.inject:guice:7.0.0'

    testImplementation 'junit:junit:4.12'
}

signing {
    sign configurations.archives
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact javadocJar

            pom {
                name = 'TypesafeConfigGuice'
                packaging = 'jar'
                description = 'TypesafeConfigGuice allows TypesafeConfig values to be injected with Guice'
                url = 'https://github.com/JoelBushart/typesafeconfig-guice'

                scm {
                    url = 'scm:git@github.com:JoelBushart/typesafeconfig-guice.git'
                    connection = 'scm:git@github.com:JoelBushart/typesafeconfig-guice.git'
                    developerConnection = 'scm:git@github.com:JoelBushart/typesafeconfig-guice.git'
                }

                licenses {
                    license {
                        name = 'The Apache Software License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution = 'repo'
                    }
                }

                developers {
                    developer {
                        id = 'racc'
                        name = 'Jason Then'
                    }
                    developer {
                        id = 'JoelBushart'
                        name = 'Joel Bushart'
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
            credentials {
                username = hasProperty('ossrhUsername') ? ossrhUsername : System.getenv('ossrhUsername')
                password = hasProperty('ossrhPassword') ? ossrhPassword : System.getenv('ossrhPassword')
            }
        }
        maven {
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
            credentials {
                username = hasProperty('ossrhUsername') ? ossrhUsername : System.getenv('ossrhUsername')
                password = hasProperty('ossrhPassword') ? ossrhPassword : System.getenv('ossrhPassword')
            }
        }
    }
}